### ISSUE TITLE
Replication Failure with Error "Unable to alter partitions"

### ISSUE THREAD

**Issue by tonyswu** [HotelsDotCom/circus-train#81] opened 2018-07-18 17:48 UTC
Source hive version: 1.2.0
Target hive version: 2.3.3

Replication for partitioned tables from older source to more recent version of HIVE failed with the error "unable to alter partitions". This was thought to be resolved in [HIVE-18767](https://issues.apache.org/jira/browse/HIVE-18767), but later we later found that the source table also needed to have stats calculated for each partition.

Exception snippet:

`2018-07-11 20:57:05,514 INFO  com.hotels.bdp.circustrain.core.replica.Replica:180 - Altering 10 existing partitions.
2018-07-11 20:57:05,932 ERROR com.hotels.bdp.circustrain.core.Locomotive:121 - Failed to replicate: gco-prod-wtp-ue1:gcoprod_dm.wtp_call_center_costs to dsp-prod-apiary-ecp-us-west-2:gcoproddm.wtp_call_center_costs.
com.hotels.bdp.circustrain.api.CircusTrainException: Unable to replicate
	at com.hotels.bdp.circustrain.core.PartitionedTableReplication.replicate(PartitionedTableReplication.java:136)
	at com.hotels.bdp.circustrain.core.Locomotive.run(Locomotive.java:114)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.hotels.bdp.circustrain.CircusTrain.main(CircusTrain.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: com.hotels.bdp.circustrain.api.metastore.MetaStoreClientException: Unable to alter partitions '[Partition(values:[2018-07-01], `

**Comment by patduin** [comment] 2018-07-19 07:35
iirc the stats calculation is something that needs to be done if you running CT on a hive version < 2.3.3 
Does it work if you calculate the stats?

**Comment by yashrajrs** [comment] 2018-07-26 17:12
Yes it  did work when we calculated stats on source

**Comment by patduin** [comment] 2018-07-27 07:43
What version of Hive is CT using, are you running that on the target or the source? or separate cluster?

**Comment by massdosage** [comment] 2018-07-27 14:53
Also, @courtsVII has just noticed that the fix for this didn't appear to go into Hive 2.3.3 even though it was merged. See https://issues.apache.org/jira/browse/HIVE-18767 for more information. So I'm not sure what we can do if the issue is in Hive itself other than ensure that the stats are set properly for all tables before replication?

**Comment by massdosage** [comment] 2019-01-04 09:01
This Hive issue above has now been resolved and should be available in the following versions of Hive:  2.4.0, 4.0.0, 3.2.0, 3.1.1, 2.3.4. So to avoid this issue either upgrade one of these Hive versions or calculate the stats on the source table prior to replication.

**Closed by massdosage** 2019-01-04 09:01 UTC
